Lamazon Store/SEDC.Lamazon/SEDC.Lamazon.Web/Models/ErrorViewModel.cs
using System;

namespace SEDC.Lamazon.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lamazon Store/SEDC.Lamazon/SEDC.Lamazon.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SEDC.Lamazon.Services.Interfaces;
using SEDC.Lamazon.Web.Models;
using SEDC.Lamazon.WebModels.Enum;
using SEDC.Lamazon.WebModels.ViewModels;
using Serilog;

namespace SEDC.Lamazon.Web.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;
        private readonly IProductService _productService;

        public OrderController(IOrderService orderService,
                               IUserService userService,
                               IProductService productService)
        {
            _orderService = orderService;
            _userService = userService;
            _productService = productService;
        }

        [Authorize(Roles = "user")]
        public IActionResult ListOrders()
        {
            try
            {
                //string userId = "3";
                UserViewModel user = _userService.GetCurrentUser(User.Identity.Name);
                List<OrderViewModel> userOrders = _orderService.GetAllOrders()
                                                                .Where(x => x.User.Id == user.Id)
                                                                .ToList();
                return View(userOrders);
            }
            catch (Exception ex)
            {
                Log.Error($"Message: {ex.Message} | Exception: {ex.InnerException}");
            }
            return PartialView("ErrorView");
        }

        [Authorize(Roles = "admin")]
        public IActionResult ListAllOrders()
        {
            try
            {
                List<OrderViewModel> orders = _orderService.GetAllOrders().ToList();
                return View(orders);
            }
            catch (Exception ex)
            {
                Log.Error($"Message: {ex.Message} | Exception: {ex.InnerException}");
            }
            return PartialView("ErrorView");
        }

        [Authorize(Roles = "user")]
        public IActionResult OrderDetails(int orderId)
        {

            try
            {
                UserViewModel user = _userService.GetCurrentUser(User.Identity.Name);
                OrderViewModel order = _orderService.GetOrderById(orderId, user.Id);

                if (order.Id > 0)
                {
                    return View("order", order);
                }
                else
                {
                    return View("Error", new ErrorViewModel());
                }
            }
            catch (Exception ex)
            {
                Log.Error($"Message: {ex.Message} | Exception: {ex.InnerException}");
            }
            return PartialView("ErrorView");
        }

        [Authorize(Roles = "user")]
        public IActionResult Order()
        {
            try
            {
                UserViewModel user = _userService.GetCurrentUser(User.Identity.Name);
                OrderViewModel order = _orderService.GetCurrentOrder(user.Id);
                return View(order);
            }
            catch (Exception ex)
            {
                Log.Error($"Message: {ex.Message} | Exception: {ex.InnerException}");
            }
            return PartialView("ErrorView");
        }

        [Authorize(Roles = "admin")]
        public IActionResult ApproveOrder(int orderId)
        {
            try
            {
                OrderViewModel order = _orderService.GetOrderById(orderId);
                _orderService.ChangeStatus(order.Id, order.User.Id, StatusTypeViewModel.Confirmed);
                return RedirectToAction("listallorders");
            }
            catch (Exception ex)
            {
                Log.Error($"Message: {ex.Message} | Exception: {ex.InnerException}");
            }
            return PartialView("ErrorView");
        }

        [Authorize(Roles = "admin")]
        public IActionResult DeclineOrder(int orderId)
        {
            try
            {
                OrderViewModel order = _orderService.GetOrderById(orderId);
                _orderService.ChangeStatus(order.Id, order.User.Id, StatusTypeViewModel.Declined);
                return RedirectToAction("listallorders");
            }
            catch (Exception ex)
            {
                Log.Error($"Message: {ex.Message} | Exception: {ex.InnerException}");
            }
            return PartialView("ErrorView");
        }

        [Authorize(Roles = "user")]
        public IActionResult ChangeStatus(int orderId, int statusId)
        {
            try
            {
                UserViewModel user = _userService.GetCurrentUser(User.Identity.Name);
                _orderService.ChangeStatus(orderId, user.Id, (StatusTypeViewModel)statusId);
                return RedirectToAction("ListOrders");
            }
            catch (Exception ex)
            {
                Log.Error($"Message: {ex.Message} | Exception: {ex.InnerException}");
            }
            return PartialView("ErrorView");
        }

        [Authorize(Roles = "user")]
        public int AddProduct(int productId)
        {
            try
            {
                UserViewModel user = _userService.GetCurrentUser(User.Identity.Name);
                OrderViewModel order = _orderService.GetCurrentOrder(user.Id);

                int result = _orderService.AddProduct(order.Id, productId, user.Id);

                if (result >= 0)
                {
                    Log.Debug($"Product was added successfully. Result: {result}");
                    return result;
                }
                else
                {
                    Log.Debug($"Product was not added successfully. Result: {result}");
                    return result;
                }
            }
            catch (Exception ex)
            {
                Log.Error($"Message: {ex.Message} | Exception: {ex.InnerException}");
            }
            return -1;
        }
    }
}

Lamazon Store/SEDC.Lamazon/SEDC.Lamazon.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SEDC.Lamazon.Services.Interfaces;
using SEDC.Lamazon.Services.Services;
using SEDC.Lamazon.WebModels.ViewModels;
using Serilog;

namespace SEDC.Lamazon.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        [Authorize(Roles = "user")]
        public IActionResult Products()
        {
            Log.Information("Fetching all products started");
            var stopwatch = new Stopwatch();
            stopwatch.Start();

            List<ProductViewModel> products = _productService.GetAllProducts().ToList();

            stopwatch.Stop();
            Log.Information($"Time for fetching all products: {stopwatch.ElapsedMilliseconds}ms");
            return View(products);
        }
    }
}

Lamazon Store/SEDC.Lamazon/SEDC.Lamazon.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using SEDC.Lamazon.Services.Interfaces;
using SEDC.Lamazon.WebModels.ViewModels;
using Serilog;

namespace SEDC.Lamazon.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IToastNotification _toastNotification;

        public UserController(IUserService userService, 
                              IToastNotification toastNotification)
        {
            _userService = userService;
            _toastNotification = toastNotification;
        }

        public IActionResult LogIn()
        {
            LoginViewModel model = new LoginViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult LogIn(LoginViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool isAdmin;
                    Log.Debug($"Authenticating user with username: {model.Username}");
                    _userService.Login(model, out isAdmin);
                    if (isAdmin)
                    {
                        _toastNotification.AddSuccessToastMessage($"Welcome {model.Username}. You are logged in as an admin!");

                        Log.Debug($"User with username {model.Username} successfully logged in! Admin user");
                        return RedirectToAction("listallorders", "order");
                    }
                    else
                    {
                        _toastNotification.AddSuccessToastMessage($"Welcome {model.Username}. You are logged in as a customer!");

                        Log.Debug($"User with username {model.Username} successfully logged in! Customer user");
                        return RedirectToAction("products", "product");
                    }
                }
            }
            catch (Exception ex)
            {
                Log.Error($"Message: {ex.Message}");
            }
            return View(model);
        }

        public IActionResult Register()
        {
            RegisterViewModel model = new RegisterViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Register(RegisterViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _userService.Register(model);
                    return RedirectToAction("products", "product");
                }
            }
            catch (Exception ex)
            {
                Log.Error($"Message: {ex.Message} | Exception: {ex.InnerException}");
            }
            return View(model);
        }

        public IActionResult LogOut()
        {
            _userService.Logout();
            return RedirectToAction("index", "home");
        }
    }
}

Lamazon Store/SEDC.Lamazon/SEDC.Lamazon.Web/Views/Shared/ErrorView.cshtml
@{     Layout = "~/Views/Shared/_Layout.cshtml";}<div id="notfound">    <div class="notfound">        <div class="notfound-404">            <h1>404</h1>            <h2>Page not found</h2>        </div>        <a asp-controller="Home" asp-action="Index" style="width:200px">Homepage</a>    </div></div>

Lamazon Store/SEDC.Lamazon/SEDC.Lamazon.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lamazon Store</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/not-found.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Lamazon Store</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>


                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                    @if (User.IsInRole("admin"))
                    {
                        <li><a asp-area="" asp-controller="Order" asp-action="ListAllOrders">All orders</a></li>
                    }
                    else
                    {
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li><a asp-area="" asp-controller="Order" asp-action="Order">Current order</a></li>
                            <li><a asp-area="" asp-controller="Order" asp-action="ListOrders">My orders</a></li>
                            <li><a asp-area="" asp-controller="Product" asp-action="Products">Products</a></li>
                        }
                    }
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li class="align-right">
                            <a asp-controller="User" asp-action="LogOut">Logout</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li class="align-right">
                            <a asp-controller="User" asp-action="Login">Login</a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; 2020 - Lamazon Store</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @await Component.InvokeAsync("NToastNotify")
    @RenderSection("Scripts", required: false)
</body>
</html>